inherit_from:
    - .rubocop_todo.yml

# Custom configuration, edit with care! This gem needs to be backwards
# compatible with Ruby 1.8:

# Fixing this issues cause some test to fail
Lint/UnifiedInteger:
  Enabled: false

# Enabling this cop cause rubocop 0.50 to crash on heredoc files
Naming/HeredocDelimiterCase:
  Enabled: false

# Enabling this cop cause rubocop 0.50 to crash on heredoc files
Naming/HeredocDelimiterNaming:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/PreferredHashMethods:
  Enabled: false

# TODO: How to warn if stabby proc is used?
Style/Lambda:
  Enabled: false

# %i supported only since ruby 2.0
Style/SymbolArray:
  EnforcedStyle: brackets
