inherit_from:
    - .rubocop_todo.yml

# Custom configuration, edit with care! This gem needs to be backwards
# compatible with Ruby 1.8:

# Fixing this issues cause some test to fail
Lint/UnifiedInteger:
  Enabled: false

# Enforce mode for compatibility with older rubies
Style/Lambda:
  EnforcedStyle: lambda

# %i supported only since ruby 2.0
Style/SymbolArray:
  EnforcedStyle: brackets
