name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.3
      uses: eregon/use-ruby-action@master
      with:
        ruby-version: 2.3.8
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        STYLE_CHECKS=true bundle exec rubocop

  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.3, 2.4, 2.5, 2.6, 2.7]
        imagemagick-version: [6.7.7-10, 6.8.9-10, 6.9.10-90, 7.0.9-20]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: eregon/use-ruby-action@master
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Update/Install packages
      run: |
        IMAGEMAGICK_VERSION=${{ matrix.imagemagick-version }} ./before_install_linux.sh
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake

  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        ruby-version: [2.3.3, 2.4.9, 2.5.7, 2.6.5, 2.7.0]
        imagemagick-version: [6.7.7-10, 6.8.9-10, 6.9.10-90, 7.0.9-20]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: eregon/use-ruby-action@master
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install ImageMagick
      run: |
        $imagemagick_version = "${{ matrix.imagemagick-version }}"
        $imagemagick_version_without_patch = $imagemagick_version.split("-")[0]
        $url = "https://ftp.icm.edu.pl/pub/graphics/ImageMagick/binaries/ImageMagick-$($imagemagick_version)-Q16-x64-dll.exe"
        $client = new-object System.Net.WebClient
        $client.DownloadFile($url, "$($(get-location).path)\imagemagick-install.exe")
        imagemagick-install.exe /VERYSILENT /TASKS=install_Devel
        SET PATH=C:\Ruby%RUBY_VERSION%\bin;C:\Program Files\ImageMagick-$($imagemagick_version_without_patch)-Q16;%PATH%
        bundle install --path=vendor/bundle
    - name: Build and test with Rake
      run: |
        bundle exec rake -rdevkit
