name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.3
      uses: eregon/use-ruby-action@master
      with:
        ruby-version: 2.3.8
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        STYLE_CHECKS=true bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.3, 2.4, 2.5, 2.6, 2.7]
        imagemagick-version:
          - { major-minor: '6.7', patch: 7, build: 10 }
          - { major-minor: '6.8', patch: 9, build: 10 }
          - { major-minor: '6.9', patch: 10, build: 90 }
          - { major-minor: '7.0', patch: 9, build: 20 }

    name: Ruby ${{ matrix.ruby-version }}, IM ${{ matrix.imagemagick-version.major-minor }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: eregon/use-ruby-action@master
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Update/Install packages
      run: |
        export IMAGEMAGICK_VERSION=${{ matrix.imagemagick-version.major-minor }}.${{ matrix.imagemagick-version.patch }}-${{ matrix.imagemagick-version.build }}
        ./before_install_linux.sh
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake
